export const LOAD_DOCUMENT_LIST_SUCCESS = 'LOAD_DOCUMENT_LIST_SUCCESS';
export const LOAD_DOCUMENT_LIST_ERROR = 'LOAD_DOCUMENT_LIST_ERROR';
export const LOAD_DOCUMENT_LIST = 'LOAD_DOCUMENT_LIST';

export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const LOAD_DOCUMENT_ERROR = 'LOAD_DOCUMENT_ERROR';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';
