export const LOAD_DOCUMENT_LIST_SUCCESS = 'LOAD_DOCUMENT_LIST_SUCCESS';
export const LOAD_DOCUMENT_LIST_ERROR = 'LOAD_DOCUMENT_LIST_ERROR';
export const LOAD_DOCUMENT_LIST = 'LOAD_DOCUMENT_LIST';

export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const LOAD_DOCUMENT_ERROR = 'LOAD_DOCUMENT_ERROR';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';

export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_ERROR = 'DELETE_DOCUMENT_ERROR';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';

export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
